# Generated by Django 4.1.1 on 2022-09-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_buygoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buy_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.buygoods'),
        ),
    ]
