# Generated by Django 4.1.1 on 2022-09-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_soldgoods_exhibitedgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exhibited_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.exhibitedgoods'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.soldgoods'),
        ),
    ]
