# Generated by Django 4.1.1 on 2022-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_categoryproduct_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.SmallIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
