# Generated by Django 4.1.1 on 2022-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_categoryproduct_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_product', to='shop.product', verbose_name='Избранное'),
        ),
    ]
